apiVersion: v1 # Descriptor conforms to version v1 of Kubernetes API
kind: Pod # Select Pod resource
metadata:
  name: graphql # The name of the pod
spec:
  containers:
    - image: graphql:v1 # Image to create the container
      name: graphql # The name of the container
      ports:
        - containerPort: 3000 # The port the app is listening on 
          protocol: TCP