apiVersion: v1
kind: Pod
metadata:
  name: graphql-v1
  
  labels:
    enviroment: stg
    project: kubernetes-graphql-v1
spec:
  containers:
    - name: graphql-kebernetes
      image: graphql
      ports:
        - containerPort: 3000
          protocol: TCP
---
apiVersion: v1
kind: Pod
metadata:
  name: graphql-v2
  labels:
    enviroment: develop
    project: kubernetes-graphql-v1
spec:
  containers:
    - name: graphql-kebernetes
      image: graphql
      ports:
        - containerPort: 3000
          protocol: TCP
---
apiVersion: v1
kind: Pod
metadata:
  name: graphql-v3
  labels:
    enviroment: production
    project: kubernetes-graphql-v1
spec:
  containers:
    - name: graphql-kebernetes
      image: graphql
      ports:
        - containerPort: 3000
          protocol: TCP